const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n||0));
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-4);
const todayISO=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

const DEFAULT={
 settings:{businessName:'DLP Burgers',open:true,pointsPer1000:10,birthdayEnabled:true,birthdayProductId:'',inactivityDays:14,inactivityCooldown:14,googleMapsApiKey:'',deliveryEnabled:true,storeLat:-34.6037,storeLng:-58.3816},
 categories:[{id:'cat-burgers',name:'Hamburguesas'},{id:'cat-sides',name:'Acompañamientos'},{id:'cat-drinks',name:'Bebidas'}],
 products:[],
 users:[{id:'admin',name:'Administrador',email:'admin@local.test',phone:'',birthDate:'',role:'admin',points:0,pushMarketing:false,pushOrders:true,lastOrderAt:null}],
 currentUserId:null,orders:[],loyalty:[],birthdayRedemptions:[],notifications:[],automationExecutions:[],cart:[],deliveryZones:[],checkoutDraft:{method:'pickup',address:'',lat:null,lng:null,zoneId:null,notes:''}
};
function migrate(raw){
 const data={...structuredClone(DEFAULT),...raw};
 data.settings={...structuredClone(DEFAULT.settings),...(raw.settings||{})};
 data.categories=Array.isArray(raw.categories)?raw.categories:structuredClone(DEFAULT.categories);
 data.products=(raw.products||[]).map(p=>({featured:false,available:true,image:'',variants:[],extras:[],removals:[],...p}));
 data.deliveryZones=Array.isArray(raw.deliveryZones)?raw.deliveryZones:[];
 data.checkoutDraft={...structuredClone(DEFAULT.checkoutDraft),...(raw.checkoutDraft||{})};
 data.cart=(raw.cart||[]).map(x=>({id:x.id||uid(),productId:x.productId,qty:x.qty||1,variantId:x.variantId||'',extraIds:x.extraIds||[],removed:x.removed||[],notes:x.notes||'',birthdayGift:!!x.birthdayGift}));
 return data;
}
function load(){try{const raw=localStorage.getItem('burgerClubMvp');return raw?migrate(JSON.parse(raw)):structuredClone(DEFAULT)}catch{return structuredClone(DEFAULT)}}
let db=load();
const save=()=>localStorage.setItem('burgerClubMvp',JSON.stringify(db));
const currentUser=()=>db.users.find(u=>u.id===db.currentUserId)||null;
const app=document.getElementById('app');
let view='home',adminView='dashboard',selectedProductId=null;
const product=id=>db.products.find(p=>p.id===id);
const category=id=>db.categories.find(c=>c.id===id);
const daysSince=date=>date?Math.floor((Date.now()-new Date(date).getTime())/86400000):Infinity;
function birthdayEligible(u){if(!db.settings.birthdayEnabled||!u?.birthDate||!db.settings.birthdayProductId)return false;const n=new Date(),b=new Date(u.birthDate+'T12:00:00');return n.getDate()===b.getDate()&&n.getMonth()===b.getMonth()&&!db.birthdayRedemptions.some(r=>r.userId===u.id&&r.year===n.getFullYear())}
function notify(title,body,url=''){const u=currentUser();db.notifications.unshift({id:uid(),userId:u?.id||null,title,body,url,createdAt:new Date().toISOString(),read:false});save();if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body})}
function requestPush(){if(!('Notification'in window))return alert('Este navegador no soporta notificaciones.');Notification.requestPermission().then(p=>alert(p==='granted'?'Notificaciones activadas.':'Permiso no concedido.'))}

function layout(content,active='home'){
 const u=currentUser();
 app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">DLP Burgers</div><div class="top-actions">${u?`<span class="pill">${u.role==='admin'?'Admin':'⭐ '+(u.points||0)+' pts'}</span><button class="btn small ghost" onclick="logout()">Salir</button>`:`<button class="btn small" onclick="go('login')">Ingresar</button>`}${u?.role==='admin'?`<button class="btn small red" onclick="goAdmin()">Panel</button>`:''}</div></header><main class="content">${content}</main>${u?.role!=='admin'?`<nav class="bottom-nav"><button class="${active==='home'?'active':''}" onclick="go('home')">⌂ Inicio</button><button class="${active==='orders'?'active':''}" onclick="go('orders')">▣ Pedidos</button><button class="${active==='points'?'active':''}" onclick="go('points')">★ Puntos</button><button class="${active==='profile'?'active':''}" onclick="go('profile')">● Perfil</button></nav>`:''}</div>`;
}
function go(v){view=v;render()} function goAdmin(v='dashboard'){view='admin';adminView=v;render()} function logout(){db.currentUserId=null;save();go('home')}
function render(){if(view==='admin')return renderAdmin();if(view==='login')return renderLogin();if(view==='menu')return renderMenu();if(view==='product')return renderProductDetail();if(view==='cart')return renderCart();if(view==='checkout')return renderCheckout();if(view==='orders')return renderOrders();if(view==='points')return renderPoints();if(view==='profile')return renderProfile();renderHome()}

function renderHome(){const u=currentUser(),b=u&&birthdayEligible(u);const featured=db.products.filter(p=>p.available!==false&&p.featured).slice(0,3);layout(`<section class="hero"><div class="card hero-main"><span class="pill ${db.settings.open?'ok':'warn'}">${db.settings.open?'● Abierto':'● Cerrado'}</span><h1>Burgers, puntos y beneficios.</h1><p>Pedí desde el celular, personalizá tu burger y sumá puntos en cada compra.</p><div class="row" style="justify-content:flex-start"><button class="btn primary" onclick="go('menu')">Ver menú</button>${!u?`<button class="btn" onclick="go('login')">Crear cuenta</button>`:''}</div></div><div class="card hero-points"><div class="metric">${u?.role==='customer'?u.points||0:0}</div><div class="metric-label">Puntos disponibles</div><div class="spacer"></div>${b?`<div class="notice success">🎂 ¡Feliz cumpleaños! Tenés un regalo disponible.</div>`:`<p class="muted">Tus beneficios aparecerán acá.</p>`}</div></section>${featured.length?`<div class="row"><h2>Destacados</h2><button class="btn small" onclick="go('menu')">Ver todo</button></div><div class="grid">${featured.map(productCard).join('')}</div>`:db.products.length?`<div class="row"><h2>Menú</h2><button class="btn small" onclick="go('menu')">Ver todo</button></div><div class="grid">${db.products.filter(p=>p.available!==false).slice(0,3).map(productCard).join('')}</div>`:`<div class="card"><h2>Catálogo listo para cargar</h2><p class="muted">Entrá al panel de administración para crear productos, variantes y extras.</p></div>`}`,'home')}
function basePrice(p){if(p.variants?.length)return Math.min(...p.variants.map(v=>Number(v.price||0)));return Number(p.price||0)}
function productCard(p){return `<article class="card product"><div class="thumb">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'🍔'}</div><div class="copy"><h3>${esc(p.name)}</h3><p class="muted">${esc(p.description||'Sin descripción')}</p>${p.variants?.length?`<span class="tag">${p.variants.length} tamaños</span>`:''}</div><div class="row action"><span class="price">${p.variants?.length?'Desde ':''}${money(basePrice(p))}</span><button class="btn primary small" onclick="openProduct('${p.id}')">Elegir</button></div></article>`}
function renderLogin(){layout(`<div class="card" style="max-width:560px;margin:auto"><h1>Ingresar o registrarse</h1><div class="form"><div class="field"><label>Email</label><input id="email" type="email" placeholder="tu@email.com"></div><div class="field"><label>Nombre (solo registro)</label><input id="name" placeholder="Tu nombre"></div><div class="field"><label>Teléfono</label><input id="phone" placeholder="11..."></div><div class="field"><label>Fecha de nacimiento</label><input id="birth" type="date"></div><div class="row" style="justify-content:flex-start"><button class="btn primary" onclick="loginOrRegister()">Continuar como cliente</button><button class="btn" onclick="adminLogin()">Entrar como admin demo</button></div><p class="muted">Demo local: la autenticación real llegará con el backend.</p></div></div>`)}
function loginOrRegister(){const email=$('#email').value.trim().toLowerCase();if(!email)return alert('Ingresá un email.');let u=db.users.find(x=>x.email===email);if(!u){const name=$('#name').value.trim();if(!name)return alert('Ingresá tu nombre.');u={id:uid(),name,email,phone:$('#phone').value.trim(),birthDate:$('#birth').value,role:'customer',points:0,pushMarketing:false,pushOrders:true,lastOrderAt:null};db.users.push(u)}db.currentUserId=u.id;save();go('home')}
function adminLogin(){db.currentUserId='admin';save();goAdmin()}

function renderMenu(){layout(`<div class="row"><div><h1>Menú</h1><p class="muted">Elegí y personalizá tu pedido.</p></div><button class="btn primary" onclick="go('cart')">Carrito (${db.cart.reduce((a,x)=>a+x.qty,0)})</button></div><div class="tabs"><button class="tab active" onclick="filterCat('',this)">Todo</button>${db.categories.map(c=>`<button class="tab" onclick="filterCat('${c.id}',this)">${esc(c.name)}</button>`).join('')}</div><div id="products" class="grid" style="margin-top:14px">${db.products.filter(p=>p.available!==false).map(productCard).join('')||'<div class="card">No hay productos cargados.</div>'}</div>`)}
function filterCat(id,el){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));el.classList.add('active');const ps=db.products.filter(p=>p.available!==false&&(!id||p.categoryId===id));$('#products').innerHTML=ps.map(productCard).join('')||'<div class="card">No hay productos en esta categoría.</div>'}
function openProduct(id){selectedProductId=id;view='product';render()}
function renderProductDetail(){const p=product(selectedProductId);if(!p)return go('menu');const variants=p.variants||[],extras=p.extras||[],removals=p.removals||[];layout(`<button class="btn small ghost" onclick="go('menu')">← Volver al menú</button><div class="spacer"></div><section class="product-detail"><div class="thumb">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'🍔'}</div><div class="card"><div class="row"><div><span class="tag">${esc(category(p.categoryId)?.name||'Producto')}</span><h1 style="margin-top:10px">${esc(p.name)}</h1></div>${p.featured?'<span class="tag">⭐ Destacado</span>':''}</div><p class="muted">${esc(p.description||'')}</p>${variants.length?`<h3>Elegí tu tamaño</h3><div class="option-group">${variants.map((v,i)=>`<label class="option"><span class="option-left"><input type="radio" name="variant" value="${v.id}" ${i===0?'checked':''} onchange="updateConfigTotal()"><strong>${esc(v.name)}</strong></span><strong>${money(v.price)}</strong></label>`).join('')}</div>`:`<div class="row"><span>Precio</span><strong>${money(p.price)}</strong></div>`}${extras.length?`<h3 style="margin-top:18px">Extras</h3><div class="option-group">${extras.map(e=>`<label class="option"><span class="option-left"><input class="extra-check" type="checkbox" value="${e.id}" onchange="updateConfigTotal()"><span>${esc(e.name)}</span></span><strong>+ ${money(e.price)}</strong></label>`).join('')}</div>`:''}${removals.length?`<h3 style="margin-top:18px">Quitar ingredientes</h3><div class="option-group">${removals.map(r=>`<label class="option"><span class="option-left"><input class="remove-check" type="checkbox" value="${esc(r)}"><span>Sin ${esc(r)}</span></span><span class="muted">Sin costo</span></label>`).join('')}</div>`:''}<div class="field" style="margin-top:18px"><label>Notas para cocina</label><textarea id="notes" placeholder="Ej: bien cocida, salsa aparte..."></textarea></div><div class="row" style="margin-top:14px"><div class="qty"><button onclick="changeQty(-1)">−</button><strong id="qty">1</strong><button onclick="changeQty(1)">+</button></div></div><div class="summary"><div><div class="mini">Total del producto</div><div id="configTotal" class="price">${money(basePrice(p))}</div></div><button class="btn red" onclick="addConfiguredToCart()">Agregar al carrito</button></div></div></section>`)}
function selectedVariant(p){const id=document.querySelector('input[name="variant"]:checked')?.value;return p.variants?.find(v=>v.id===id)||null}
function configUnitPrice(){const p=product(selectedProductId);if(!p)return 0;const v=selectedVariant(p);let total=v?Number(v.price):Number(p.price||0);document.querySelectorAll('.extra-check:checked').forEach(ch=>{const e=p.extras.find(x=>x.id===ch.value);if(e)total+=Number(e.price||0)});return total}
function updateConfigTotal(){const q=Number($('#qty')?.textContent||1);if($('#configTotal'))$('#configTotal').textContent=money(configUnitPrice()*q)}
function changeQty(d){const el=$('#qty');let q=Math.max(1,Number(el.textContent||1)+d);el.textContent=q;updateConfigTotal()}
function addConfiguredToCart(){const p=product(selectedProductId);if(!p)return;const v=selectedVariant(p);if(p.variants?.length&&!v)return alert('Elegí una variante.');const extraIds=[...document.querySelectorAll('.extra-check:checked')].map(x=>x.value);const removed=[...document.querySelectorAll('.remove-check:checked')].map(x=>x.value);const qty=Number($('#qty').textContent||1);db.cart.push({id:uid(),productId:p.id,qty,variantId:v?.id||'',extraIds,removed,notes:$('#notes').value.trim(),birthdayGift:false});save();notify('Agregado al carrito',p.name);go('cart')}
function cartUnitPrice(item,p){if(item.birthdayGift)return 0;const v=p.variants?.find(x=>x.id===item.variantId);let n=v?Number(v.price):Number(p.price||0);(item.extraIds||[]).forEach(id=>{const e=p.extras?.find(x=>x.id===id);if(e)n+=Number(e.price||0)});return n}
function cartItemLabel(item,p){const v=p.variants?.find(x=>x.id===item.variantId),extras=(item.extraIds||[]).map(id=>p.extras?.find(e=>e.id===id)?.name).filter(Boolean);return [v?.name,extras.length?`Extras: ${extras.join(', ')}`:'',(item.removed||[]).length?`Sin: ${item.removed.join(', ')}`:'',item.notes?`Nota: ${item.notes}`:''].filter(Boolean).join(' · ')}
function renderCart(){const items=db.cart.map(i=>({i,p:product(i.productId)})).filter(x=>x.p),subtotal=items.reduce((a,x)=>a+cartUnitPrice(x.i,x.p)*x.i.qty,0),u=currentUser(),birthday=u&&birthdayEligible(u);layout(`<div class="row"><h1>Tu pedido</h1><button class="btn" onclick="go('menu')">Seguir comprando</button></div><div class="list">${items.map(({i,p})=>`<div class="item"><div class="row"><div><strong>${i.qty}× ${esc(p.name)}${i.birthdayGift?' 🎂':''}</strong><div class="muted mini">${esc(cartItemLabel(i,p))}</div></div><strong>${money(cartUnitPrice(i,p)*i.qty)}</strong></div><div class="spacer"></div><button class="btn small danger" onclick="removeCart('${i.id}')">Quitar</button></div>`).join('')||'<div class="card">Tu carrito está vacío.</div>'}</div>${birthday?`<div class="card" style="margin-top:14px"><h3>🎂 Regalo de cumpleaños</h3><p class="muted">Agregá sin cargo el producto definido por administración.</p><button class="btn" onclick="addBirthdayGift()">Agregar regalo</button></div>`:''}<div class="card" style="margin-top:14px"><div class="row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="row"><span>Delivery</span><strong>${money(0)}</strong></div><hr><div class="row"><span class="price">Total</span><span class="price">${money(subtotal)}</span></div><div class="spacer"></div><button class="btn primary" ${items.length?'':'disabled'} onclick="go('checkout')">Continuar</button></div>`)}
function removeCart(id){db.cart=db.cart.filter(x=>x.id!==id);save();render()}
function addBirthdayGift(){const u=currentUser();if(!birthdayEligible(u))return alert('El beneficio no está disponible.');const p=product(db.settings.birthdayProductId);if(!p)return alert('El producto de cumpleaños ya no existe.');db.cart.push({id:uid(),productId:p.id,qty:1,variantId:p.variants?.[0]?.id||'',extraIds:[],removed:[],notes:'Regalo de cumpleaños',birthdayGift:true});save();render()}
function checkout(){const u=currentUser();if(!u||u.role!=='customer')return alert('Ingresá como cliente antes de confirmar.');if(!db.settings.open)return alert('El local figura cerrado.');const d=db.checkoutDraft||{};if(d.method==='delivery'){if(!d.address||d.lat==null||d.lng==null)return alert('Seleccioná una dirección válida desde Google Maps.');const z=zoneForPoint(Number(d.lat),Number(d.lng));if(!z)return alert('La dirección está fuera de las zonas de entrega.');d.zoneId=z.id}const items=db.cart.map(i=>{const p=product(i.productId);return p?{...i,name:p.name,unitPrice:cartUnitPrice(i,p),configuration:cartItemLabel(i,p)}:null}).filter(Boolean);if(!items.length)return;const subtotal=items.reduce((a,i)=>a+i.unitPrice*i.qty,0);const zone=d.method==='delivery'?db.deliveryZones.find(z=>z.id===d.zoneId):null;if(zone&&subtotal<Number(zone.minOrder||0))return alert(`El pedido mínimo para ${zone.name} es ${money(zone.minOrder)}.`);const deliveryFee=zone?Number(zone.fee||0):0,total=subtotal+deliveryFee,order={id:uid(),number:String(db.orders.length+1).padStart(4,'0'),userId:u.id,items,subtotal,deliveryFee,total,fulfillment:d.method,deliveryAddress:d.method==='delivery'?d.address:'',deliveryLat:d.method==='delivery'?Number(d.lat):null,deliveryLng:d.method==='delivery'?Number(d.lng):null,deliveryZoneId:zone?.id||null,deliveryZoneName:zone?.name||'',deliveryNotes:d.notes||'',status:'pending',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),pointsCredited:false};db.orders.unshift(order);if(items.some(i=>i.birthdayGift))db.birthdayRedemptions.push({id:uid(),userId:u.id,year:new Date().getFullYear(),orderId:order.id});db.cart=[];db.checkoutDraft=structuredClone(DEFAULT.checkoutDraft);save();notify('Pedido recibido',`Tu pedido #${order.number} fue recibido.`);go('orders')}

function statusText(s){return({pending:'Recibido',accepted:'Confirmado',preparing:'Preparando',ready:'Listo',on_the_way:'En camino',delivered:'Entregado',cancelled:'Cancelado'})[s]||s}
function renderOrders(){const u=currentUser();if(!u)return layout(`<div class="card"><h1>Tus pedidos</h1><p>Ingresá para ver tu historial.</p><button class="btn primary" onclick="go('login')">Ingresar</button></div>`,'orders');const os=db.orders.filter(o=>o.userId===u.id);layout(`<h1>Mis pedidos</h1><div class="list">${os.map(o=>`<div class="item"><div class="row"><div><strong>Pedido #${o.number}</strong><div class="status ${o.status}">${statusText(o.status)}</div></div><strong>${money(o.total)}</strong></div><p class="muted">${o.items.map(i=>`${i.qty}× ${esc(i.name)}${i.configuration?` · ${esc(i.configuration)}`:''}`).join('<br>')}</p></div>`).join('')||'<div class="card">Todavía no hiciste pedidos.</div>'}</div>`,'orders')}
function renderPoints(){const u=currentUser();if(!u)return layout(`<div class="card"><h1>Puntos</h1><p>Ingresá para ver tus puntos.</p></div>`,'points');const tx=db.loyalty.filter(x=>x.userId===u.id);layout(`<div class="two"><div class="card"><div class="metric">${u.points||0}</div><div class="metric-label">Puntos disponibles</div><p class="muted">Actualmente sumás ${db.settings.pointsPer1000} puntos por cada $1.000 en pedidos entregados.</p></div><div class="card"><h2>Movimientos</h2>${tx.map(t=>`<div class="item row"><span>${esc(t.description)}</span><strong>+${t.points}</strong></div>`).join('')||'<p class="muted">Todavía no hay movimientos.</p>'}</div></div>`,'points')}
function renderProfile(){const u=currentUser();if(!u)return layout(`<div class="card"><h1>Perfil</h1><button class="btn primary" onclick="go('login')">Ingresar</button></div>`,'profile');layout(`<div class="two"><div class="card"><h1>Perfil</h1><div class="form"><div class="field"><label>Nombre</label><input id="profName" value="${esc(u.name)}"></div><div class="field"><label>Teléfono</label><input id="profPhone" value="${esc(u.phone||'')}"></div><div class="field"><label>Fecha de nacimiento</label><input id="profBirth" type="date" value="${esc(u.birthDate||'')}"></div><button class="btn primary" onclick="saveProfile()">Guardar</button></div></div><div class="card"><h2>Notificaciones</h2><label class="option"><span>Estados de pedidos</span><input id="pushOrders" type="checkbox" ${u.pushOrders?'checked':''} onchange="savePushPrefs()"></label><label class="option" style="margin-top:8px"><span>Promociones</span><input id="pushMarketing" type="checkbox" ${u.pushMarketing?'checked':''} onchange="savePushPrefs()"></label><div class="spacer"></div><button class="btn" onclick="requestPush()">Activar permiso del navegador</button></div></div>`,'profile')}
function saveProfile(){const u=currentUser();u.name=$('#profName').value.trim()||u.name;u.phone=$('#profPhone').value.trim();u.birthDate=$('#profBirth').value;save();render()}
function savePushPrefs(){const u=currentUser();u.pushOrders=$('#pushOrders').checked;u.pushMarketing=$('#pushMarketing').checked;save()}

function renderAdmin(){if(currentUser()?.role!=='admin')return go('login');const entries=[['dashboard','Dashboard'],['orders','Pedidos'],['products','Productos'],['categories','Categorías'],['customers','Clientes'],['loyalty','Puntos'],['birthday','Cumpleaños'],['delivery','Delivery'],['campaigns','Campañas'],['settings','Configuración']];const nav=`<div class="admin-nav">${entries.map(([k,n])=>`<button class="btn ${adminView===k?'primary':''}" onclick="goAdmin('${k}')">${n}</button>`).join('')}</div><div class="spacer"></div>`;let body='';if(adminView==='orders')body=adminOrders();else if(adminView==='products')body=adminProducts();else if(adminView==='categories')body=adminCategories();else if(adminView==='customers')body=adminCustomers();else if(adminView==='loyalty')body=adminLoyalty();else if(adminView==='birthday')body=adminBirthday();else if(adminView==='delivery')body=adminDelivery();else if(adminView==='campaigns')body=adminCampaigns();else if(adminView==='settings')body=adminSettings();else body=adminDashboard();layout(nav+body)}
function adminDashboard(){const t=todayISO(),os=db.orders.filter(o=>o.createdAt.slice(0,10)===t);return `<h1>Dashboard</h1><div class="grid"><div class="card"><div class="metric">${db.orders.filter(o=>o.status==='pending').length}</div><div class="metric-label">Pedidos nuevos</div></div><div class="card"><div class="metric">${db.products.filter(p=>p.available===false).length}</div><div class="metric-label">Productos agotados</div></div><div class="card"><div class="metric">${money(os.filter(o=>o.status==='delivered').reduce((a,o)=>a+o.total,0))}</div><div class="metric-label">Ventas entregadas hoy</div></div></div><div class="card" style="margin-top:14px"><h2>Acciones rápidas</h2><div class="row" style="justify-content:flex-start"><button class="btn red" onclick="goAdmin('products')">Cargar producto</button><button class="btn" onclick="goAdmin('orders')">Gestionar pedidos</button></div></div>`}
function adminOrders(){return `<h1>Pedidos</h1><div class="list">${db.orders.map(o=>{const u=db.users.find(x=>x.id===o.userId);return `<div class="item"><div class="row"><div><strong>#${o.number} · ${esc(u?.name||'Cliente')}</strong><div class="status ${o.status}">${statusText(o.status)}</div></div><strong>${money(o.total)}</strong></div><p>${o.items.map(i=>`${i.qty}× ${esc(i.name)}${i.configuration?` · <span class="muted">${esc(i.configuration)}</span>`:''}`).join('<br>')}</p><div class="row" style="justify-content:flex-start">${nextStatusButtons(o)}</div></div>`}).join('')||'<div class="card">No hay pedidos.</div>'}</div>`}
function nextStatusButtons(o){if(o.status==='pending')return `<button class="btn red small" onclick="setOrderStatus('${o.id}','accepted')">Aceptar</button><button class="btn danger small" onclick="setOrderStatus('${o.id}','cancelled')">Cancelar</button>`;if(o.status==='accepted')return `<button class="btn red small" onclick="setOrderStatus('${o.id}','preparing')">Preparando</button>`;if(o.status==='preparing')return `<button class="btn red small" onclick="setOrderStatus('${o.id}','ready')">Listo</button>`;if(o.status==='ready')return `<button class="btn red small" onclick="setOrderStatus('${o.id}','on_the_way')">En camino</button>`;if(o.status==='on_the_way')return `<button class="btn red small" onclick="setOrderStatus('${o.id}','delivered')">Entregado</button>`;return ''}
function setOrderStatus(id,status){const o=db.orders.find(x=>x.id===id);if(!o)return;o.status=status;o.updatedAt=new Date().toISOString();const u=db.users.find(x=>x.id===o.userId);if(status==='on_the_way'&&u?.pushOrders)db.notifications.unshift({id:uid(),userId:u.id,title:'🛵 ¡Tu pedido está en camino!',body:`Tu pedido #${o.number} ya salió del local.`,createdAt:new Date().toISOString(),read:false});if(status==='delivered'&&u){u.lastOrderAt=new Date().toISOString();if(!o.pointsCredited){const pts=Math.floor(o.total/1000)*Number(db.settings.pointsPer1000||0);if(pts){u.points=(u.points||0)+pts;db.loyalty.unshift({id:uid(),userId:u.id,orderId:o.id,points:pts,description:`Pedido #${o.number}`,createdAt:new Date().toISOString()})}o.pointsCredited=true}}save();render()}

function parseNamedPrices(text){return text.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [name,...rest]=line.split('|');return {id:uid(),name:name.trim(),price:Number(rest.join('|').trim()||0)}}).filter(x=>x.name)}
function parseLines(text){return text.split('\n').map(x=>x.trim()).filter(Boolean)}
function adminProducts(){return `<div class="two"><div class="card"><h1>Productos</h1><div class="list">${db.products.map(p=>`<div class="item"><div class="row"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(category(p.categoryId)?.name||'Sin categoría')} · ${p.variants?.length?'Desde '+money(basePrice(p)):money(p.price)} · ${p.available!==false?'Disponible':'Agotado'}</div></div><div><button class="btn small" onclick="toggleAvailable('${p.id}')">${p.available!==false?'Agotar':'Activar'}</button> <button class="btn small danger" onclick="deleteProduct('${p.id}')">Eliminar</button></div></div><div class="spacer"></div><div class="mini">${p.variants?.length?`${p.variants.length} variantes · `:''}${p.extras?.length?`${p.extras.length} extras · `:''}${p.removals?.length?`${p.removals.length} removibles`:''}</div></div>`).join('')||'<p class="muted">Todavía no hay productos.</p>'}</div></div><div class="card"><h2>Nuevo producto</h2><div class="form"><div class="field"><label>Nombre</label><input id="pname"></div><div class="field"><label>Categoría</label><select id="pcat">${db.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Descripción</label><textarea id="pdesc"></textarea></div><div class="field"><label>Precio base (si no usa variantes)</label><input id="pprice" type="number" min="0" placeholder="0"></div><div class="field"><label>URL de foto (opcional)</label><input id="pimage" placeholder="https://..."></div><label><input id="pfeatured" type="checkbox"> Mostrar como destacado</label><div class="field"><label>Variantes — una por línea: Nombre | Precio</label><textarea id="pvariants" placeholder="Simple | 8000\nDoble | 9500\nTriple | 11000"></textarea></div><div class="field"><label>Extras — uno por línea: Nombre | Precio</label><textarea id="pextras" placeholder="Cheddar extra | 1200\nBacon | 1800"></textarea></div><div class="field"><label>Ingredientes removibles — uno por línea</label><textarea id="premovals" placeholder="Cebolla\nPepinillos\nSalsa"></textarea></div><button class="btn red" onclick="createProduct()">Guardar producto</button></div></div></div>`}
function createProduct(){const name=$('#pname').value.trim(),price=Number($('#pprice').value||0),variants=parseNamedPrices($('#pvariants').value),extras=parseNamedPrices($('#pextras').value),removals=parseLines($('#premovals').value);if(!name)return alert('Completá el nombre.');if(!variants.length&&price<0)return alert('Ingresá un precio válido.');db.products.push({id:uid(),name,categoryId:$('#pcat').value,description:$('#pdesc').value.trim(),price,image:$('#pimage').value.trim(),featured:$('#pfeatured').checked,available:true,variants,extras,removals});save();render()}
function deleteProduct(id){if(!confirm('¿Eliminar producto?'))return;db.products=db.products.filter(p=>p.id!==id);db.cart=db.cart.filter(i=>i.productId!==id);save();render()}
function toggleAvailable(id){const p=product(id);if(!p)return;p.available=p.available===false;save();render()}
function adminCategories(){return `<div class="two"><div class="card"><h1>Categorías</h1><div class="list">${db.categories.map(c=>`<div class="item row"><strong>${esc(c.name)}</strong><button class="btn small danger" onclick="deleteCategory('${c.id}')">Eliminar</button></div>`).join('')}</div></div><div class="card"><h2>Nueva categoría</h2><div class="field"><label>Nombre</label><input id="catName" placeholder="Combos"></div><div class="spacer"></div><button class="btn red" onclick="createCategory()">Crear categoría</button></div></div>`}
function createCategory(){const name=$('#catName').value.trim();if(!name)return;db.categories.push({id:uid(),name});save();render()}
function deleteCategory(id){if(db.products.some(p=>p.categoryId===id))return alert('Esta categoría tiene productos. Movelos o eliminálos primero.');if(!confirm('¿Eliminar categoría?'))return;db.categories=db.categories.filter(c=>c.id!==id);save();render()}
function adminCustomers(){const cs=db.users.filter(u=>u.role==='customer');return `<h1>Clientes</h1><div class="card"><table><thead><tr><th>Nombre</th><th>Email</th><th>Puntos</th><th>Último pedido</th><th>Promo</th></tr></thead><tbody>${cs.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.points||0}</td><td>${u.lastOrderAt?new Date(u.lastOrderAt).toLocaleDateString('es-AR'):'—'}</td><td>${u.pushMarketing?'Sí':'No'}</td></tr>`).join('')}</tbody></table></div>`}
function adminLoyalty(){return `<div class="two"><div class="card"><h1>Programa de puntos</h1><div class="field"><label>Puntos cada $1.000</label><input id="pointsRate" type="number" value="${db.settings.pointsPer1000}"></div><div class="spacer"></div><button class="btn red" onclick="savePointsRate()">Guardar</button></div><div class="card"><h2>Movimientos</h2>${db.loyalty.slice(0,10).map(t=>`<div class="item row"><span>${esc(t.description)}</span><strong>+${t.points}</strong></div>`).join('')||'<p class="muted">Sin movimientos.</p>'}</div></div>`}
function savePointsRate(){db.settings.pointsPer1000=Number($('#pointsRate').value||0);save();render()}
function adminBirthday(){return `<div class="two"><div class="card"><h1>Beneficio de cumpleaños</h1><label><input id="bEnabled" type="checkbox" ${db.settings.birthdayEnabled?'checked':''}> Activado</label><div class="spacer"></div><div class="field"><label>Producto de regalo</label><select id="bProduct"><option value="">Sin definir</option>${db.products.map(p=>`<option value="${p.id}" ${db.settings.birthdayProductId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><button class="btn red" onclick="saveBirthday()">Guardar</button></div><div class="card"><h2>Canjes</h2>${db.birthdayRedemptions.map(r=>{const u=db.users.find(x=>x.id===r.userId);return `<div class="item">${esc(u?.name||'Cliente')} · ${r.year}</div>`}).join('')||'<p class="muted">Todavía no hay canjes.</p>'}</div></div>`}
function saveBirthday(){db.settings.birthdayEnabled=$('#bEnabled').checked;db.settings.birthdayProductId=$('#bProduct').value;save();render()}
function adminCampaigns(){return `<div class="two"><div class="card"><h1>Reactivación</h1><div class="field"><label>Días sin pedir</label><input id="inactiveDays" type="number" value="${db.settings.inactivityDays}"></div><div class="field"><label>Cooldown (días)</label><input id="cooldown" type="number" value="${db.settings.inactivityCooldown}"></div><button class="btn red" onclick="saveCampaignSettings()">Guardar</button> <button class="btn" onclick="runInactiveAutomation()">Ejecutar ahora</button></div><div class="card"><h2>Historial</h2>${db.automationExecutions.slice(0,15).map(x=>{const u=db.users.find(a=>a.id===x.userId);return `<div class="item"><strong>${esc(u?.name||'Cliente')}</strong><div class="muted">${new Date(x.createdAt).toLocaleString('es-AR')} · ${esc(x.result)}</div></div>`}).join('')||'<p class="muted">Sin ejecuciones.</p>'}</div></div>`}
function saveCampaignSettings(){db.settings.inactivityDays=Number($('#inactiveDays').value||14);db.settings.inactivityCooldown=Number($('#cooldown').value||14);save();render()}
function runInactiveAutomation(){const days=Number(db.settings.inactivityDays||14),cd=Number(db.settings.inactivityCooldown||14);let sent=0;db.users.filter(u=>u.role==='customer'&&u.pushMarketing&&daysSince(u.lastOrderAt)>=days).forEach(u=>{const last=db.automationExecutions.find(x=>x.userId===u.id&&x.type==='inactive');if(last&&daysSince(last.createdAt)<cd)return;db.notifications.unshift({id:uid(),userId:u.id,title:'🍔 Te extrañamos',body:`¡Hola ${u.name}! Tenés ${u.points||0} puntos disponibles.`,createdAt:new Date().toISOString(),read:false});db.automationExecutions.unshift({id:uid(),userId:u.id,type:'inactive',result:'push creada',createdAt:new Date().toISOString()});sent++});save();alert(`Notificaciones creadas: ${sent}`);render()}
function adminSettings(){return `<div class="card" style="max-width:650px"><h1>Configuración</h1><div class="form"><div class="field"><label>Nombre del negocio</label><input id="bizName" value="${esc(db.settings.businessName)}"></div><label><input id="bizOpen" type="checkbox" ${db.settings.open?'checked':''}> Local abierto</label><button class="btn red" onclick="saveSettings()">Guardar</button><button class="btn danger" onclick="resetDemo()">Restablecer datos demo</button></div></div>`}
function saveSettings(){db.settings.businessName=$('#bizName').value.trim()||'DLP Burgers';db.settings.open=$('#bizOpen').checked;save();render()}
function resetDemo(){if(!confirm('Esto borrará todos los datos locales.'))return;db=structuredClone(DEFAULT);save();go('home')}


// --- V4: Google Maps + zonas de delivery ---
let deliveryMap=null,deliveryDraftPath=[],deliveryDraftPolygon=null,customerMap=null,customerMarker=null,customerAutocomplete=null;
function activeZones(){return (db.deliveryZones||[]).filter(z=>z.active!==false).sort((a,b)=>Number(b.priority||0)-Number(a.priority||0))}
function pointInPolygon(lat,lng,path){let inside=false;for(let i=0,j=path.length-1;i<path.length;j=i++){const yi=Number(path[i].lat),xi=Number(path[i].lng),yj=Number(path[j].lat),xj=Number(path[j].lng);const hit=((yi>lat)!=(yj>lat))&&(lng<(xj-xi)*(lat-yi)/((yj-yi)||1e-12)+xi);if(hit)inside=!inside}return inside}
function zoneForPoint(lat,lng){return activeZones().find(z=>Array.isArray(z.path)&&z.path.length>=3&&pointInPolygon(lat,lng,z.path))||null}
function googleMapsReady(){return !!(window.google&&google.maps)}
function loadGoogleMaps(cb){if(googleMapsReady())return cb?.();const key=(db.settings.googleMapsApiKey||'').trim();if(!key)return;window.__dlpMapsCallbacks=window.__dlpMapsCallbacks||[];if(cb)window.__dlpMapsCallbacks.push(cb);if(document.getElementById('dlp-google-maps'))return;window.__dlpMapsLoaded=()=>{(window.__dlpMapsCallbacks||[]).splice(0).forEach(fn=>{try{fn()}catch(e){console.error(e)}})};const sc=document.createElement('script');sc.id='dlp-google-maps';sc.async=true;sc.defer=true;sc.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&libraries=places&callback=__dlpMapsLoaded`;sc.onerror=()=>alert('No se pudo cargar Google Maps. Revisá la API key y sus restricciones.');document.head.appendChild(sc)}
function adminDelivery(){const zones=db.deliveryZones||[];setTimeout(()=>loadGoogleMaps(initDeliveryMap),30);return `<div class="two"><div><div class="card"><div class="row"><div><h1>Delivery por zonas</h1><p class="muted">Dibujá polígonos sobre Google Maps. Cada zona puede tener tarifa, pedido mínimo y prioridad propia.</p></div><span class="tag">V4</span></div><div class="field"><label>Google Maps API key</label><input id="mapsKey" type="password" value="${esc(db.settings.googleMapsApiKey||'')}" placeholder="AIza..."></div><div class="row" style="justify-content:flex-start;margin-top:10px"><button class="btn red" onclick="saveMapsKey()">Guardar y cargar mapa</button><button class="btn" onclick="useStoreLocation()">Usar mi ubicación como local</button></div>${!db.settings.googleMapsApiKey?'<div class="notice" style="margin-top:12px">Para ver Google Maps necesitás una API key con Maps JavaScript API y Places API habilitadas. La estructura de zonas ya queda preparada.</div>':''}</div><div class="card" style="margin-top:14px"><div id="deliveryMap" class="map-box"><div class="map-empty">Google Maps aparecerá acá al configurar la API key.</div></div><div class="row" style="justify-content:flex-start;margin-top:10px"><button class="btn" onclick="clearDeliveryDraft()">Borrar dibujo</button><span class="muted mini">Tocá al menos 3 puntos del mapa para formar el polígono.</span></div></div></div><div><div class="card"><h2>Nueva zona</h2><div class="form"><div class="field"><label>Nombre</label><input id="zoneName" placeholder="Zona Centro"></div><div class="field"><label>Valor de envío</label><input id="zoneFee" type="number" min="0" placeholder="1500"></div><div class="field"><label>Pedido mínimo</label><input id="zoneMin" type="number" min="0" placeholder="0"></div><div class="field"><label>Prioridad</label><input id="zonePriority" type="number" value="1"><span class="muted mini">Si dos zonas se superponen, gana la prioridad más alta.</span></div><button class="btn red" onclick="saveDeliveryZone()">Guardar zona dibujada</button></div></div><div class="card" style="margin-top:14px"><h2>Zonas creadas</h2><div class="list">${zones.map(z=>`<div class="item"><div class="row"><div><strong>${esc(z.name)}</strong><div class="muted mini">Envío ${money(z.fee)} · mínimo ${money(z.minOrder||0)} · prioridad ${z.priority||0}</div></div><span class="tag ${z.active===false?'off':''}">${z.active===false?'Inactiva':'Activa'}</span></div><div class="row" style="justify-content:flex-start;margin-top:10px"><button class="btn small" onclick="focusZone('${z.id}')">Ver</button><button class="btn small" onclick="toggleZone('${z.id}')">${z.active===false?'Activar':'Desactivar'}</button><button class="btn small danger" onclick="deleteZone('${z.id}')">Eliminar</button></div></div>`).join('')||'<p class="muted">Todavía no creaste zonas.</p>'}</div></div></div></div>`}
function saveMapsKey(){db.settings.googleMapsApiKey=$('#mapsKey').value.trim();save();location.reload()}
function initDeliveryMap(){const el=$('#deliveryMap');if(!el||!googleMapsReady())return;deliveryMap=new google.maps.Map(el,{center:{lat:Number(db.settings.storeLat),lng:Number(db.settings.storeLng)},zoom:14,mapTypeControl:false,streetViewControl:false});new google.maps.Marker({map:deliveryMap,position:{lat:Number(db.settings.storeLat),lng:Number(db.settings.storeLng)},title:'DLP Burgers'});activeZones().forEach(z=>new google.maps.Polygon({map:deliveryMap,paths:z.path,strokeWeight:2,strokeOpacity:.9,fillOpacity:.18,clickable:false}));deliveryMap.addListener('click',e=>{deliveryDraftPath.push({lat:e.latLng.lat(),lng:e.latLng.lng()});drawDeliveryDraft()})}
function drawDeliveryDraft(){if(!deliveryMap||!googleMapsReady())return;if(deliveryDraftPolygon)deliveryDraftPolygon.setMap(null);deliveryDraftPolygon=new google.maps.Polygon({map:deliveryMap,paths:deliveryDraftPath,strokeWeight:3,fillOpacity:.22})}
function clearDeliveryDraft(){deliveryDraftPath=[];if(deliveryDraftPolygon){deliveryDraftPolygon.setMap(null);deliveryDraftPolygon=null}}
function saveDeliveryZone(){if(deliveryDraftPath.length<3)return alert('Dibujá al menos 3 puntos en el mapa.');const name=$('#zoneName').value.trim();if(!name)return alert('Ingresá un nombre para la zona.');db.deliveryZones.push({id:uid(),name,fee:Number($('#zoneFee').value||0),minOrder:Number($('#zoneMin').value||0),priority:Number($('#zonePriority').value||0),active:true,path:deliveryDraftPath.map(p=>({...p}))});save();deliveryDraftPath=[];render()}
function toggleZone(id){const z=db.deliveryZones.find(x=>x.id===id);if(!z)return;z.active=z.active===false;save();render()}
function deleteZone(id){if(!confirm('¿Eliminar esta zona de delivery?'))return;db.deliveryZones=db.deliveryZones.filter(z=>z.id!==id);save();render()}
function focusZone(id){const z=db.deliveryZones.find(x=>x.id===id);if(!z||!deliveryMap||!googleMapsReady())return;const b=new google.maps.LatLngBounds();z.path.forEach(p=>b.extend(p));deliveryMap.fitBounds(b)}
function useStoreLocation(){if(!navigator.geolocation)return alert('Geolocalización no disponible.');navigator.geolocation.getCurrentPosition(pos=>{db.settings.storeLat=pos.coords.latitude;db.settings.storeLng=pos.coords.longitude;save();render()},()=>alert('No se pudo obtener tu ubicación.'))}
function renderCheckout(){const items=db.cart.map(i=>({i,p:product(i.productId)})).filter(x=>x.p),subtotal=items.reduce((a,x)=>a+cartUnitPrice(x.i,x.p)*x.i.qty,0),d=db.checkoutDraft||structuredClone(DEFAULT.checkoutDraft),zone=d.zoneId?db.deliveryZones.find(z=>z.id===d.zoneId):null,fee=d.method==='delivery'&&zone?Number(zone.fee||0):0;setTimeout(()=>{if(d.method==='delivery')loadGoogleMaps(initCustomerDelivery)},30);layout(`<div class="row"><div><h1>Entrega</h1><p class="muted">Elegí retiro o delivery.</p></div><button class="btn" onclick="go('cart')">← Carrito</button></div><div class="two"><div class="card"><div class="option-group"><label class="option"><span class="option-left"><input type="radio" name="fulfillment" value="pickup" ${d.method!=='delivery'?'checked':''} onchange="setFulfillment('pickup')"><strong>Retiro en el local</strong></span><span class="muted">$0</span></label><label class="option"><span class="option-left"><input type="radio" name="fulfillment" value="delivery" ${d.method==='delivery'?'checked':''} onchange="setFulfillment('delivery')"><strong>Delivery</strong></span><span class="muted">Según zona</span></label></div>${d.method==='delivery'?`<div class="spacer"></div><div class="field"><label>Buscá tu domicilio en Google Maps</label><input id="deliveryAddress" value="${esc(d.address||'')}" placeholder="Calle, número, localidad"></div><div class="row" style="justify-content:flex-start;margin-top:10px"><button class="btn small" onclick="useCustomerLocation()">⌖ Usar mi ubicación</button></div><div id="customerMap" class="map-box small-map"><div class="map-empty">${db.settings.googleMapsApiKey?'Cargando Google Maps…':'El administrador debe configurar Google Maps.'}</div></div><div id="zoneResult" class="notice ${zone?'success':''}" style="margin-top:10px">${zone?`Zona: <strong>${esc(zone.name)}</strong> · envío ${money(zone.fee)}`:'Seleccioná una dirección para calcular el envío.'}</div><div class="field" style="margin-top:10px"><label>Piso / departamento / referencias</label><textarea id="deliveryNotes" oninput="saveDeliveryNotes(this.value)" placeholder="Ej: 2° B, timbre no funciona...">${esc(d.notes||'')}</textarea></div>`:''}</div><div class="card"><h2>Resumen</h2><div class="row"><span>Productos</span><strong>${money(subtotal)}</strong></div><div class="row"><span>Envío</span><strong>${money(fee)}</strong></div><hr><div class="row"><span class="price">Total</span><span class="price">${money(subtotal+fee)}</span></div>${zone&&subtotal<Number(zone.minOrder||0)?`<div class="notice" style="margin-top:10px">Pedido mínimo en ${esc(zone.name)}: ${money(zone.minOrder)}</div>`:''}<div class="spacer"></div><button class="btn primary" onclick="checkout()">Confirmar pedido</button></div></div>`,'home')}
function setFulfillment(method){db.checkoutDraft={...db.checkoutDraft,method,zoneId:null};save();render()}
function saveDeliveryNotes(v){db.checkoutDraft.notes=v;save()}
function initCustomerDelivery(){const el=$('#customerMap'),input=$('#deliveryAddress');if(!el||!input||!googleMapsReady())return;customerMap=new google.maps.Map(el,{center:{lat:Number(db.settings.storeLat),lng:Number(db.settings.storeLng)},zoom:14,mapTypeControl:false,streetViewControl:false});activeZones().forEach(z=>new google.maps.Polygon({map:customerMap,paths:z.path,strokeWeight:2,fillOpacity:.12,clickable:false}));customerMarker=new google.maps.Marker({map:customerMap});customerAutocomplete=new google.maps.places.Autocomplete(input,{fields:['formatted_address','geometry','place_id'],types:['address']});customerAutocomplete.addListener('place_changed',()=>{const place=customerAutocomplete.getPlace();if(!place.geometry?.location)return alert('Elegí una sugerencia válida de Google Maps.');applyCustomerPoint(place.geometry.location.lat(),place.geometry.location.lng(),place.formatted_address||input.value)});if(db.checkoutDraft.lat!=null)applyCustomerPoint(Number(db.checkoutDraft.lat),Number(db.checkoutDraft.lng),db.checkoutDraft.address||'',false)}
function applyCustomerPoint(lat,lng,address,rerender=true){const z=zoneForPoint(lat,lng);db.checkoutDraft={...db.checkoutDraft,address,lat,lng,zoneId:z?.id||null};save();if(customerMarker){customerMarker.setPosition({lat,lng});customerMap.panTo({lat,lng});customerMap.setZoom(16)}if(rerender)render()}
function useCustomerLocation(){if(!navigator.geolocation)return alert('Geolocalización no disponible.');navigator.geolocation.getCurrentPosition(pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude;if(googleMapsReady()){const geocoder=new google.maps.Geocoder();geocoder.geocode({location:{lat,lng}},(res,status)=>applyCustomerPoint(lat,lng,status==='OK'&&res[0]?res[0].formatted_address:'Mi ubicación actual'))}else applyCustomerPoint(lat,lng,'Mi ubicación actual')},()=>alert('No pudimos acceder a tu ubicación.'))}

render();
