const $ = s => document.querySelector(s);
const money = n => new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n||0));
const todayISO=()=>new Date().toISOString().slice(0,10);
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-4);

const DEFAULT = {
  settings:{businessName:'Burger Club',open:true,pointsPer1000:10,birthdayEnabled:true,birthdayProductId:'',birthdayWindow:0,inactivityDays:14,inactivityCooldown:14},
  categories:[{id:'cat-burgers',name:'Hamburguesas'},{id:'cat-sides',name:'Acompañamientos'},{id:'cat-drinks',name:'Bebidas'}],
  products:[],
  users:[{id:'admin',name:'Administrador',email:'admin@local.test',phone:'',birthDate:'',role:'admin',points:0,pushMarketing:false,pushOrders:true,lastOrderAt:null}],
  currentUserId:null,
  orders:[], loyalty:[], rewards:[], birthdayRedemptions:[], notifications:[], automationExecutions:[], cart:[]
};
const load=()=>{const raw=localStorage.getItem('burgerClubMvp'); if(!raw) return structuredClone(DEFAULT); try{return {...structuredClone(DEFAULT),...JSON.parse(raw)}}catch{return structuredClone(DEFAULT)}};
let db=load();
const save=()=>localStorage.setItem('burgerClubMvp',JSON.stringify(db));
const currentUser=()=>db.users.find(u=>u.id===db.currentUserId)||null;
const isAdmin=()=>currentUser()?.role==='admin';
const app=document.getElementById('app');
let view='home', adminView='dashboard';

function notify(title,body,url=''){
  const u=currentUser();
  const rec={id:uid(),userId:u?.id||null,title,body,url,createdAt:new Date().toISOString(),read:false}; db.notifications.unshift(rec); save();
  if('Notification'in window && Notification.permission==='granted') new Notification(title,{body});
}
function requestPush(){ if(!('Notification'in window)) return alert('Este navegador no soporta notificaciones.'); Notification.requestPermission().then(p=>alert(p==='granted'?'Notificaciones activadas.':'Permiso no concedido.')); }
function daysSince(date){if(!date)return Infinity;return Math.floor((Date.now()-new Date(date).getTime())/86400000)}
function birthdayEligible(u){if(!db.settings.birthdayEnabled||!u?.birthDate||!db.settings.birthdayProductId)return false;const now=new Date();const bd=new Date(u.birthDate+'T12:00:00');const isDay=now.getDate()===bd.getDate()&&now.getMonth()===bd.getMonth();if(!isDay)return false;return !db.birthdayRedemptions.some(r=>r.userId===u.id&&r.year===now.getFullYear());}
function product(id){return db.products.find(p=>p.id===id)}

function layout(content,active='home'){
 const u=currentUser();
 app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">${db.settings.businessName}</div><div class="top-actions">${u?`<span class="pill">${u.role==='admin'?'Admin':'⭐ '+u.points+' pts'}</span><button class="btn small ghost" onclick="logout()">Salir</button>`:`<button class="btn small" onclick="go('login')">Ingresar</button>`}${u?.role==='admin'?`<button class="btn small primary" onclick="goAdmin()">Panel</button>`:''}</div></header><main class="content">${content}</main>${u?.role!=='admin'?`<nav class="bottom-nav"><button class="${active==='home'?'active':''}" onclick="go('home')">Inicio</button><button class="${active==='orders'?'active':''}" onclick="go('orders')">Pedidos</button><button class="${active==='points'?'active':''}" onclick="go('points')">Puntos</button><button class="${active==='profile'?'active':''}" onclick="go('profile')">Perfil</button></nav>`:''}</div>`;
}
function go(v){view=v;render()}; function goAdmin(v='dashboard'){adminView=v;view='admin';render()}
function logout(){db.currentUserId=null;save();go('home')}

function render(){if(view==='admin')return renderAdmin(); if(view==='login')return renderLogin(); if(view==='menu')return renderMenu(); if(view==='cart')return renderCart(); if(view==='orders')return renderOrders(); if(view==='points')return renderPoints(); if(view==='profile')return renderProfile(); return renderHome();}
function renderHome(){const u=currentUser(); const birthday=u&&birthdayEligible(u); layout(`<section class="hero"><div class="card"><span class="pill ${db.settings.open?'ok':'warn'}">${db.settings.open?'● Abierto':'● Cerrado'}</span><h1 style="margin-top:16px">Hamburguesas, puntos y beneficios.</h1><p class="muted">Pedí desde el celular, seguí tu pedido y acumulá puntos en cada compra.</p><div class="row" style="justify-content:flex-start"><button class="btn primary" onclick="go('menu')">Ver menú</button>${!u?`<button class="btn" onclick="go('login')">Crear cuenta</button>`:''}</div></div><div class="card"><div class="metric">${u?.role==='customer'?u.points:0}</div><div class="metric-label">Puntos disponibles</div><div class="spacer"></div>${birthday?`<div class="notice success">🎂 ¡Feliz cumpleaños! Tenés un regalo disponible.</div>`:`<p class="muted">Tus beneficios aparecerán acá.</p>`}</div></section>${db.products.length?`<div class="row"><h2>Destacados</h2><button class="btn small" onclick="go('menu')">Ver todo</button></div><div class="grid">${db.products.filter(p=>p.available!==false).slice(0,3).map(productCard).join('')}</div>`:`<div class="card"><h2>Catálogo listo para cargar</h2><p class="muted">El administrador todavía no cargó productos. Entrá al panel para comenzar.</p></div>`}`,'home')}
function productCard(p){return `<article class="card product"><div class="thumb">🍔</div><div><h3>${p.name}</h3><p class="muted">${p.description||'Sin descripción'}</p></div><div class="row"><span class="price">${money(p.price)}</span><button class="btn primary small" onclick="addToCart('${p.id}')">Agregar</button></div></article>`}
function renderLogin(){layout(`<div class="card" style="max-width:560px;margin:auto"><h1>Ingresar o registrarse</h1><div class="form"><div class="field"><label>Email</label><input id="email" type="email" placeholder="tu@email.com"></div><div class="field"><label>Nombre (solo para registro)</label><input id="name" placeholder="Tu nombre"></div><div class="field"><label>Teléfono</label><input id="phone" placeholder="11..."></div><div class="field"><label>Fecha de nacimiento</label><input id="birth" type="date"></div><div class="row" style="justify-content:flex-start"><button class="btn primary" onclick="loginOrRegister()">Continuar como cliente</button><button class="btn" onclick="adminLogin()">Entrar como admin demo</button></div><p class="muted">MVP local: no usa contraseña todavía. La autenticación real se conectará a Supabase.</p></div></div>`)}
function loginOrRegister(){const email=$('#email').value.trim().toLowerCase(); if(!email)return alert('Ingresá un email.'); let u=db.users.find(x=>x.email===email);if(!u){const name=$('#name').value.trim();if(!name)return alert('Ingresá tu nombre para registrarte.');u={id:uid(),name,email,phone:$('#phone').value.trim(),birthDate:$('#birth').value,role:'customer',points:0,pushMarketing:false,pushOrders:true,lastOrderAt:null};db.users.push(u)}db.currentUserId=u.id;save();go('home')}
function adminLogin(){db.currentUserId='admin';save();goAdmin()}
function renderMenu(){const cats=db.categories; layout(`<div class="row"><div><h1>Menú</h1><p class="muted">Elegí tus productos.</p></div><button class="btn primary" onclick="go('cart')">Carrito (${db.cart.reduce((a,x)=>a+x.qty,0)})</button></div><div class="tabs">${cats.map(c=>`<button class="tab" onclick="filterCat('${c.id}',this)">${c.name}</button>`).join('')}</div><div id="products" class="grid" style="margin-top:14px">${db.products.filter(p=>p.available!==false).map(productCard).join('')||'<div class="card">No hay productos cargados.</div>'}</div>`)}
function filterCat(id,el){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));el.classList.add('active');$('#products').innerHTML=db.products.filter(p=>p.available!==false&&p.categoryId===id).map(productCard).join('')||'<div class="card">No hay productos en esta categoría.</div>'}
function addToCart(id){const found=db.cart.find(x=>x.productId===id); if(found)found.qty++; else db.cart.push({productId:id,qty:1});save();notify('Agregado al carrito',product(id)?.name||'Producto');render()}
function renderCart(){const items=db.cart.map(x=>({...x,p:product(x.productId)})).filter(x=>x.p); const subtotal=items.reduce((a,x)=>a+x.p.price*x.qty,0); const u=currentUser(); const birthday=u&&birthdayEligible(u); layout(`<h1>Tu pedido</h1><div class="list">${items.map(x=>`<div class="item row"><div><strong>${x.qty}× ${x.p.name}</strong><div class="muted">${money(x.p.price)} c/u</div></div><div><strong>${money(x.p.price*x.qty)}</strong> <button class="btn small danger" onclick="removeCart('${x.productId}')">Quitar</button></div></div>`).join('')||'<div class="card">Tu carrito está vacío.</div>'}</div>${birthday?`<div class="card" style="margin-top:14px"><h3>🎂 Regalo de cumpleaños</h3><p class="muted">Podés agregar sin cargo el producto definido por el administrador.</p><button class="btn" onclick="addBirthdayGift()">Agregar regalo</button></div>`:''}<div class="card" style="margin-top:14px"><div class="row"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="row"><span>Delivery</span><strong>${money(0)}</strong></div><hr style="border:0;border-top:1px solid var(--line)"><div class="row"><span class="price">Total</span><span class="price">${money(subtotal)}</span></div><div class="spacer"></div><button class="btn primary" ${items.length?'':'disabled'} onclick="checkout()">Confirmar pedido</button></div>`)}
function removeCart(id){db.cart=db.cart.filter(x=>x.productId!==id);save();render()}
function addBirthdayGift(){const u=currentUser();if(!birthdayEligible(u))return alert('El beneficio no está disponible.');const pid=db.settings.birthdayProductId;const p=product(pid);if(!p)return alert('El producto de cumpleaños ya no existe.');if(!db.cart.find(x=>x.productId===pid&&x.birthdayGift))db.cart.push({productId:pid,qty:1,birthdayGift:true});save();render()}
function checkout(){const u=currentUser();if(!u)return go('login');const items=db.cart.map(x=>({...x,p:product(x.productId)})).filter(x=>x.p);if(!items.length)return;let total=0;const orderItems=items.map(x=>{const free=!!x.birthdayGift;const unit=free?0:x.p.price;total+=unit*x.qty;return {productId:x.p.id,name:x.p.name,qty:x.qty,unitPrice:unit,birthdayGift:free}});const order={id:uid(),number:1000+db.orders.length+1,userId:u.id,status:'pending',items:orderItems,total,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),deliveryType:'delivery'};db.orders.unshift(order);if(orderItems.some(x=>x.birthdayGift)){db.birthdayRedemptions.push({id:uid(),userId:u.id,year:new Date().getFullYear(),orderId:order.id,createdAt:new Date().toISOString()})}db.cart=[];save();notify('Pedido recibido',`Tu pedido #${order.number} fue recibido.`);go('orders')}
function renderOrders(){const u=currentUser();if(!u)return go('login');const orders=db.orders.filter(o=>o.userId===u.id);layout(`<h1>Mis pedidos</h1><div class="list">${orders.map(o=>`<div class="item"><div class="row"><strong>Pedido #${o.number}</strong><span class="status ${o.status}">${statusText(o.status)}</span></div><p>${o.items.map(i=>`${i.qty}× ${i.name}${i.birthdayGift?' 🎂':''}`).join('<br>')}</p><div class="row"><span class="muted">${new Date(o.createdAt).toLocaleString('es-AR')}</span><strong>${money(o.total)}</strong></div></div>`).join('')||'<div class="card">Todavía no hiciste pedidos.</div>'}</div>`,'orders')}
function statusText(s){return ({pending:'Pendiente',accepted:'Aceptado',preparing:'Preparando',ready:'Listo',on_the_way:'En camino',delivered:'Entregado',cancelled:'Cancelado'})[s]||s}
function renderPoints(){const u=currentUser();if(!u)return go('login');const tx=db.loyalty.filter(t=>t.userId===u.id);layout(`<section class="hero"><div class="card"><div class="metric">${u.points}</div><div class="metric-label">Puntos disponibles</div></div><div class="card"><h3>Regla actual</h3><p>Por cada $1.000: <strong>${db.settings.pointsPer1000} puntos</strong></p></div></section><div class="card"><h2>Movimientos</h2><div class="list">${tx.map(t=>`<div class="row item"><span>${t.description}</span><strong>${t.points>0?'+':''}${t.points}</strong></div>`).join('')||'<p class="muted">Todavía no hay movimientos.</p>'}</div></div>`,'points')}
function renderProfile(){const u=currentUser();if(!u)return go('login');layout(`<div class="card"><h1>${u.name}</h1><p>${u.email}</p><p class="muted">Cumpleaños: ${u.birthDate||'Sin cargar'}</p><hr style="border:0;border-top:1px solid var(--line)"><h3>Notificaciones</h3><label><input type="checkbox" ${u.pushOrders?'checked':''} onchange="togglePref('pushOrders',this.checked)"> Estado de mis pedidos</label><br><br><label><input type="checkbox" ${u.pushMarketing?'checked':''} onchange="togglePref('pushMarketing',this.checked)"> Promociones y reactivación</label><div class="spacer"></div><button class="btn" onclick="requestPush()">Activar notificaciones del navegador</button></div>`,'profile')}
function togglePref(k,v){currentUser()[k]=v;save()}

function renderAdmin(){if(!isAdmin())return go('login');const nav=`<div class="admin-nav">${[['dashboard','Resumen'],['orders','Pedidos'],['products','Productos'],['customers','Clientes'],['loyalty','Puntos'],['birthday','Cumpleaños'],['campaigns','Campañas'],['settings','Configuración']].map(([k,n])=>`<button class="tab ${adminView===k?'active':''}" onclick="goAdmin('${k}')">${n}</button>`).join('')}</div><div class="spacer"></div>`;let body='';if(adminView==='orders')body=adminOrders();else if(adminView==='products')body=adminProducts();else if(adminView==='customers')body=adminCustomers();else if(adminView==='loyalty')body=adminLoyalty();else if(adminView==='birthday')body=adminBirthday();else if(adminView==='campaigns')body=adminCampaigns();else if(adminView==='settings')body=adminSettings();else body=adminDashboard();layout(nav+body)}
function adminDashboard(){const today=todayISO();const todayOrders=db.orders.filter(o=>o.createdAt.slice(0,10)===today);return `<h1>Dashboard</h1><div class="grid"><div class="card"><div class="metric">${db.orders.filter(o=>o.status==='pending').length}</div><div class="metric-label">Pedidos nuevos</div></div><div class="card"><div class="metric">${todayOrders.filter(o=>o.status==='delivered').length}</div><div class="metric-label">Entregados hoy</div></div><div class="card"><div class="metric">${money(todayOrders.filter(o=>o.status==='delivered').reduce((a,o)=>a+o.total,0))}</div><div class="metric-label">Ventas entregadas hoy</div></div></div><div class="card" style="margin-top:14px"><h2>Acciones rápidas</h2><div class="row" style="justify-content:flex-start;flex-wrap:wrap"><button class="btn primary" onclick="goAdmin('orders')">Gestionar pedidos</button><button class="btn" onclick="goAdmin('products')">Cargar producto</button><button class="btn" onclick="runInactiveAutomation()">Ejecutar reactivación 14 días</button></div></div>`}
function adminOrders(){return `<div class="row"><h1>Pedidos</h1></div><div class="list">${db.orders.map(o=>{const u=db.users.find(x=>x.id===o.userId);return `<div class="item"><div class="row"><div><strong>#${o.number} · ${u?.name||'Cliente'}</strong><div class="status ${o.status}">${statusText(o.status)}</div></div><strong>${money(o.total)}</strong></div><p>${o.items.map(i=>`${i.qty}× ${i.name}${i.birthdayGift?' 🎂':''}`).join('<br>')}</p><div class="row" style="justify-content:flex-start;flex-wrap:wrap">${nextStatusButtons(o)}</div></div>`}).join('')||'<div class="card">No hay pedidos.</div>'}</div>`}
function nextStatusButtons(o){if(o.status==='pending')return `<button class="btn primary small" onclick="setOrderStatus('${o.id}','accepted')">Aceptar</button><button class="btn danger small" onclick="setOrderStatus('${o.id}','cancelled')">Cancelar</button>`;if(o.status==='accepted')return `<button class="btn primary small" onclick="setOrderStatus('${o.id}','preparing')">Preparando</button>`;if(o.status==='preparing')return `<button class="btn primary small" onclick="setOrderStatus('${o.id}','ready')">Listo</button>`;if(o.status==='ready')return `<button class="btn primary small" onclick="setOrderStatus('${o.id}','on_the_way')">En camino</button>`;if(o.status==='on_the_way')return `<button class="btn primary small" onclick="setOrderStatus('${o.id}','delivered')">Entregado</button>`;return ''}
function setOrderStatus(id,status){const o=db.orders.find(x=>x.id===id);if(!o)return;o.status=status;o.updatedAt=new Date().toISOString();const u=db.users.find(x=>x.id===o.userId);if(status==='on_the_way'&&u?.pushOrders){db.notifications.unshift({id:uid(),userId:u.id,title:'🛵 ¡Tu pedido está en camino!',body:`Tu pedido #${o.number} ya salió del local.`,url:`orders/${o.id}`,createdAt:new Date().toISOString(),read:false})}if(status==='delivered'){u.lastOrderAt=new Date().toISOString();if(!o.pointsCredited){const pts=Math.floor(o.total/1000)*Number(db.settings.pointsPer1000||0);if(pts){u.points=(u.points||0)+pts;db.loyalty.unshift({id:uid(),userId:u.id,orderId:o.id,points:pts,description:`Pedido #${o.number}`,createdAt:new Date().toISOString()})}o.pointsCredited=true}}save();render()}
function adminProducts(){return `<div class="two"><div class="card"><h1>Productos</h1><div class="list">${db.products.map(p=>`<div class="item row"><div><strong>${p.name}</strong><div class="muted">${money(p.price)} · ${p.available!==false?'Disponible':'Agotado'}</div></div><button class="btn small danger" onclick="deleteProduct('${p.id}')">Eliminar</button></div>`).join('')||'<p class="muted">Todavía no hay productos.</p>'}</div></div><div class="card"><h2>Nuevo producto</h2><div class="form"><div class="field"><label>Nombre</label><input id="pname"></div><div class="field"><label>Categoría</label><select id="pcat">${db.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div class="field"><label>Descripción</label><textarea id="pdesc"></textarea></div><div class="field"><label>Precio</label><input id="pprice" type="number" min="0"></div><button class="btn primary" onclick="createProduct()">Guardar producto</button></div></div></div>`}
function createProduct(){const name=$('#pname').value.trim(),price=Number($('#pprice').value);if(!name||price<0)return alert('Completá nombre y precio.');db.products.push({id:uid(),name,description:$('#pdesc').value.trim(),price,categoryId:$('#pcat').value,available:true});save();render()}
function deleteProduct(id){if(!confirm('¿Eliminar producto?'))return;db.products=db.products.filter(p=>p.id!==id);save();render()}
function adminCustomers(){const customers=db.users.filter(u=>u.role==='customer');return `<h1>Clientes</h1><div class="card"><table><thead><tr><th>Nombre</th><th>Email</th><th>Puntos</th><th>Último pedido</th><th>Push promo</th></tr></thead><tbody>${customers.map(u=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.points}</td><td>${u.lastOrderAt?new Date(u.lastOrderAt).toLocaleDateString('es-AR'):'—'}</td><td>${u.pushMarketing?'Sí':'No'}</td></tr>`).join('')}</tbody></table></div>`}
function adminLoyalty(){return `<div class="two"><div class="card"><h1>Programa de puntos</h1><div class="field"><label>Puntos cada $1.000</label><input id="pointsRate" type="number" value="${db.settings.pointsPer1000}"></div><div class="spacer"></div><button class="btn primary" onclick="savePointsRate()">Guardar</button></div><div class="card"><h2>Movimientos recientes</h2>${db.loyalty.slice(0,10).map(t=>`<div class="item row"><span>${t.description}</span><strong>+${t.points}</strong></div>`).join('')||'<p class="muted">Sin movimientos.</p>'}</div></div>`}
function savePointsRate(){db.settings.pointsPer1000=Number($('#pointsRate').value||0);save();render()}
function adminBirthday(){return `<div class="two"><div class="card"><h1>Beneficio de cumpleaños</h1><label><input id="bEnabled" type="checkbox" ${db.settings.birthdayEnabled?'checked':''}> Activado</label><div class="spacer"></div><div class="field"><label>Producto de regalo</label><select id="bProduct"><option value="">Sin definir</option>${db.products.map(p=>`<option value="${p.id}" ${db.settings.birthdayProductId===p.id?'selected':''}>${p.name}</option>`).join('')}</select></div><button class="btn primary" onclick="saveBirthday()">Guardar</button></div><div class="card"><h2>Canjes</h2>${db.birthdayRedemptions.map(r=>{const u=db.users.find(x=>x.id===r.userId);return `<div class="item">${u?.name||'Cliente'} · ${r.year}</div>`}).join('')||'<p class="muted">Todavía no hay canjes.</p>'}</div></div>`}
function saveBirthday(){db.settings.birthdayEnabled=$('#bEnabled').checked;db.settings.birthdayProductId=$('#bProduct').value;save();render()}
function adminCampaigns(){return `<div class="two"><div class="card"><h1>Automatización de inactividad</h1><div class="field"><label>Días sin pedir</label><input id="inactiveDays" type="number" value="${db.settings.inactivityDays}"></div><div class="field"><label>Cooldown entre mensajes (días)</label><input id="cooldown" type="number" value="${db.settings.inactivityCooldown}"></div><button class="btn primary" onclick="saveCampaignSettings()">Guardar regla</button><button class="btn" style="margin-left:8px" onclick="runInactiveAutomation()">Ejecutar ahora</button></div><div class="card"><h2>Historial</h2>${db.automationExecutions.slice(0,15).map(x=>{const u=db.users.find(a=>a.id===x.userId);return `<div class="item"><strong>${u?.name||'Cliente'}</strong><div class="muted">${new Date(x.createdAt).toLocaleString('es-AR')} · ${x.result}</div></div>`}).join('')||'<p class="muted">Sin ejecuciones.</p>'}</div></div>`}
function saveCampaignSettings(){db.settings.inactivityDays=Number($('#inactiveDays').value||14);db.settings.inactivityCooldown=Number($('#cooldown').value||14);save();render()}
function runInactiveAutomation(){const days=Number(db.settings.inactivityDays||14),cd=Number(db.settings.inactivityCooldown||14);let sent=0;db.users.filter(u=>u.role==='customer'&&u.pushMarketing&&daysSince(u.lastOrderAt)>=days).forEach(u=>{const last=db.automationExecutions.find(x=>x.userId===u.id&&x.type==='inactive');if(last&&daysSince(last.createdAt)<cd)return;const body=`¡Hola ${u.name}! Hace ${u.lastOrderAt?daysSince(u.lastOrderAt):days+'+'} días que no te vemos. Tenés ${u.points||0} puntos disponibles.`;db.notifications.unshift({id:uid(),userId:u.id,title:'🍔 Te extrañamos',body,url:'menu',createdAt:new Date().toISOString(),read:false});db.automationExecutions.unshift({id:uid(),userId:u.id,type:'inactive',result:'push creada',createdAt:new Date().toISOString()});sent++});save();alert(`Automatización ejecutada. Notificaciones creadas: ${sent}`);render()}
function adminSettings(){return `<div class="card" style="max-width:650px"><h1>Configuración</h1><div class="form"><div class="field"><label>Nombre del negocio</label><input id="bizName" value="${db.settings.businessName}"></div><label><input id="bizOpen" type="checkbox" ${db.settings.open?'checked':''}> Local abierto</label><button class="btn primary" onclick="saveSettings()">Guardar</button><button class="btn danger" onclick="resetDemo()">Restablecer datos demo</button></div></div>`}
function saveSettings(){db.settings.businessName=$('#bizName').value.trim()||'Burger Club';db.settings.open=$('#bizOpen').checked;save();render()}
function resetDemo(){if(!confirm('Esto borrará todos los datos locales.'))return;db=structuredClone(DEFAULT);save();go('home')}

render();
